"""add email column

Revision ID: 7593b3f978e1
Revises: 55ef465f9946
Create Date: 2020-01-15 03:41:27.066239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7593b3f978e1'
down_revision = '55ef465f9946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
